### ISSUE TITLE
Pause macro does not work correctly

### ISSUE THREAD

**Issue by DarkPako84** [jschuh/klipper-macros#100]
After the last update, immediately after pressing the resume command, the hotend does not reposition correctly and extrudes into the air. It also does not resume the correct speed but goes much slower.

**Comment by jschuh** [comment]
I can't think of any recent changes to part of the macros, and I can't debug an issue without more context. So, please follow the [troubleshooting and bug reporting guidance](https://github.com/jschuh/klipper-macros#troubleshooting), and I'll reopen if this if there's more detail that identifies an issue.

**Comment by hardmax** [comment]
Hi,

Same problem for Here. After M601, pause occour (Park with beep) after that the nozzle go over print in correct position., but appear the printer do an extra park, again, noozle go over print but not in layer and resume print but with z in other layer.

I think that in my config are a second pause and resume, and the second one last the actual layer heigh.

I hope that this help

Regards

**Comment by jschuh** [comment]
Looking a bit more closely, I'm certain that a7a34ab1604643a591ed4af62fb7188c800a781e is just wrong, so I already reverted it from main. You should be able to just update as normal and I expect everything will be fine.

**Comment by hardmax** [comment]
Yes, now all are ok, are working...thanks for you work...

A new feature that I like propuse you is add a varible to end print macro to increase last retract. This is because the new easy change nozzle like E3D Revo and Rapido and others need that at finish print with a long retract releases the filament from the nozzle when the print finishes. As a result, the nozzle can be unscrewed without heating up and removing the filament first.  

Thanks againg
