### ISSUE TITLE
[BUG]variable_start_end_park_x missing

### ISSUE THREAD

**Issue by SarcasmRules** [jschuh/klipper-macros#161]
Not really a bug but more of a request; though, I think it is a bug, can you also add a "variable_start_end_park_x" (as there's a end_park_y variable). Currently it is (end) parking it at X0.0. I'm using sensorless homing and before moving X it will move the toolhead X-5 (move away from X potential endstop) causing chatter and skipping of belts (wear). I'm bypassing it currently by adding a forced move macro to the print_start (before _PRINT_START_PHASE_PREHEAT) but a user adjustable end_park is better? Perhaps not everyone likes the toolhead parked at X0 YMAX?

**Comment by jschuh** [comment]
Feature ideas belong in [the discussions section](https://github.com/jschuh/klipper-macros/discussions/categories/ideas).

Regarding start_end_park_y, that's a special case to handle the fact that normally the Y axis is parked in the opposite location at the end of the print, so it's easier to remove the part. The Z and X don't need that special handling, because the X doesn't change and by default the Z is relative to the last extruder position (so setting the normal park_x and park_z options works fine).
