### ISSUE TITLE
m109/m190 temps

### ISSUE THREAD

**Issue by solo2424** [jschuh/klipper-macros#25]
For some reaon my m109 and m190 temps seem odd. Can you tell me where this info is being pulled from? For extruder is is 108 and for bed it is 62. I don't think I have thoses values set anywhere in my slicers. My goal is to higher the extruder and also I would prefer if they both preheat at the same time. As of now, it is doing the bed first.  Any assistance would be great! I appreciate this plugin.

**Comment by jschuh** [comment]
I think you're asking about the different stages in the `START_PRINT` macro? I use these macros for a few very different printers, so there are a number of options in [global.cfg](https://github.com/jschuh/klipper-macros/blob/main/globals.cfg) to adjust the exact behavior at print start.

For example, I've found that if I preheat the extruder to full temp at startup I get filament oozing onto the bed during the bed probing sequence, so `variable_start_extruder_preheat_scale` defaults to half (0.5) of the target temp to prevent this. However, if that's not a concern you can add `variable_start_extruder_preheat_scale: 1.0` to your `[gcode_macro _km_options]`, which will immediately begin heating your extruder to full temp at print start.

I've also found that if I want the bed really stable at the target temp prior to printing it helps to overshoot the the target by a few degrees and then let it settle back down. However, if you just want the bed to go straight to the target you can set `variable_start_bed_heat_overshoot: 2.0` in your `[gcode_macro _km_options]`.

I admit that the defaults for these options are quite conservative, because that's what I find most convenient for my personal use. However, all of it should be sufficiently configurable.
