### ISSUE TITLE
klipper crashed when pressing lcd button

### ISSUE THREAD

**Issue by Supruh** [jschuh/klipper-macros#37]
Klipper will crash when pressing the button on my lcd. The screen is a default ender 3 screen. I am only using the lcd macro, and I can add any more info if needed

**Comment by jschuh** [comment]
You can't use only the LCD macro file, since it depends on other macros in the package. Did you follow the installation [instructions here](https://github.com/jschuh/klipper-macros#installation)?

That stated, nothing in this macro package should be able to cause Klipper to crash. Running a malformed macro (i.e. including the LCD macro without required dependencies) certainly may cause Klipper to initiate a printer shutdown, but a crash would be very surprising.

**Comment by Supruh** [comment]
It might not have been a crash then, I’ll have to double check. I didn’t want to use all of the macros, so I didn’t install it through the instructions although I can if that will fix it, so I guess I can just ask if it’s possible to disable some of the macros

**Comment by jschuh** [comment]
Sorry, it's a package of macros, so it's just not possible to use them independently.
