### ISSUE TITLE
Modify START/END/PAUSE/RESUME print permanently

### ISSUE THREAD

**Issue by Sc0ut71** [jschuh/klipper-macros#86]
Meanwhile, I apologize if this is not the right section, I hope I'm not making mistakes.
I have a Smart Filament Sensor and I would like to enable it at print start (and resume) and disable it at print end (and pause). I had changed the start/end/pause/resume macros to do what I wanted but when I updated the changes were discarded. I saw that in _km_globals you can add variables for starting the print (so I assume starting the sensor). But I can't find anything for end, pause and resume. How can I add rows that are then not deleted on update? I had also put, at the end of the print, a macro that would turn off the printer when I reached 50°, I would gladly implement this macro as well as the filament sensor. Thank you

**Comment by jschuh** [comment]
Now I remember why I stopped working on the runout check in `PRINT_START`. It's not actually possible to pause the print on runout, because the pause event doesn't take effect until the next input line is read, which can't happen until after `PRINT_START` completes.

Anyway, back to your original question, this is the [relevant portion of the readme](https://github.com/jschuh/klipper-macros#print_start) that demonstrates how to wrap macros:

```
[gcode_macro PRINT_START]
rename_existing: KM_PRINT_START
gcode:
  # Put macro code here to run before PRINT_START.
  KM_PRINT_START {rawparams}
  # Put macro code here to run after PRINT_START but before the print gcode
```
